version: 2.1

jobs:
  Build and Test:
    docker:
      - image: lennint/python-browsers-brew:latest

    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install requirements and run tests"
          command: |
            npm install
            npm start &
            git submodule add https://github.com/LenninTroyaQA/tests-api
            cd tests-api
            pytest --alluredir=allure-results || true
            allure generate allure-results -o allure-report
            sleep 10

      - store_artifacts:
          path: tests-api/allure-report

workflows:
  Testing:
    jobs:
      - Tests:
          filters:
            branches:
              only: /^release-.*$/
